server:
  port: 7001
spring:
  application:
    name: orbit-api-gateway
#  cloud:
#    gateway:
#      routes:
#      - id: i18n-orbit
#        uri: lb://orbit-i18n
#        predicates:
#        - Path=/lang/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/


orbit:
  cors:
    mapping: /**
    allow-credentials: true
    allowed-headers: Authorization, content-type
    allowed-methods: GET,POST,PUT,DELETE,PATCH
    max-age: 3600