server:
  port: 6999
spring:
  application:
    name: orbit-configurations
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inmaytide/orbit
          search-paths: spring-config-repository
