version: "3.5"

networks:
  app_net:
    external: true

services:
  # api gateway start
  api-gateway:
    build:
      context: ./orbit-api-gateway
      args:
        JAR_FILE: target/api-gateway.jar
    ports:
      - '0.0.0.0:${API_PORT}:7001'
    networks:
      - default
      - app_net
    container_name: orbit-api-gateway

  # i18n start
  i18n:
    build:
      context: ./orbit-i18n
      args:
        JAR_FILE: target/i18n.jar
    container_name: orbit-i18n
    networks:
      - default
      - app_net

  # authorization start
  authorization:
    build:
      context: ./orbit-authorization
      args:
        JAR_FILE: target/authorization.jar
    container_name: orbit-authorization
    networks:
      - default
      - app_net

  # captcha
  captcha:
    container_name: orbit-captcha
    networks:
      - default
      - app_net
    extra_hosts:
      - "redis-server:${REDIS_SERVER}"
    build:
      context: ./orbit-captcha
      args:
        JAR_FILE: target/captcha.jar

  data-dictionary:
    container_name: orbit-data-dictionary
    networks:
      - default
      - app_net
    extra_hosts:
      - "redis-server:${REDIS_SERVER}"
      - "mysql-server:${MYSQL_SERVER}"
    build:
      context: ./orbit-data-dictionary
      args:
        JAR_FILE: target/data-dictionary.jar

  system-management:
    container_name: orbit-system-management
    networks:
      - default
      - app_net
    extra_hosts:
      - "redis-server:${REDIS_SERVER}"
      - "mysql-server:${MYSQL_SERVER}"
    build:
      context: ./orbit-system-management
      args:
        JAR_FILE: target/system-management.jar