server:
  port: 7007
spring:
  application:
    name: orbit-data-dictionary
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/db_orbit?characterEncoding=UTF-8&useSSL=false
  jpa:
   properties:
     hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
     hibernate.show_sql: true
  #   hibernate.hbm2ddl.auto: update
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    redis:
      repositories:
        enabled: false



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/

logging:
  level:
    root: info
    com.inmaytide.orbit.dictionary: debug