profile: dev
server:
  port: 7006
spring:
  application:
    name: orbit-captcha
  redis:
    host: redis-server
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    root: info
    com.inmaytide.orbit: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://orbit-discovery:7000/eureka/
