server:
  port: 7005

spring:
  application:
    name: orbit-system-management
  datasource:
    url: jdbc:mysql://localhost:3306/db_orbit?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.show_sql: true
#      hibernate.use_sql_comments: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
#logging:
#  level:
#    root: info
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace